### ISSUE TITLE
Problem with multiple show correct answer buttons

### ISSUE THREAD

**Issue by jovit** [jovit/fy-moodle#26]
![whatsapp image 2017-11-27 at 9 27 29 pm](https://user-images.githubusercontent.com/7768469/33295034-74e4a656-d3ba-11e7-93a4-847ae52d93c7.jpeg)
Multiple correct answer buttons are being shown, this could be related to the multiple answers feature recently merged.

**Comment by jovit** [comment]
All the buttons show the same answer, so it's not a breaking bug, but it's bad for the user experience.

**Comment by carlosamds** [comment]
Solved on #27
